language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

env:
    - SYMFONY_VERSION=2.7
    - SYMFONY_VERSION=2.8
    - SYMFONY_VERSION=3.2

before_script:
    - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist --no-interaction --no-progress

notifications:
    email:
        - antalaron@antalaron.hu
